### ISSUE TITLE
Plugin doesn't work: Cannot find module 'browser-sync'

### ISSUE THREAD

**Issue by Izhaki** [gurunate/nodemon-browsersync-webpack-plugin#3]
package.json:

```json
  "dependencies": {
    "browsersync": "0.0.1-security",
    "chalk": "^1.1.3",
    "lodash": "^4.17.2",
    "nodemon": "^1.11.0"
  },
```

Note that `browsersync` on [npm point to a security holding package](https://www.npmjs.com/package/browsersync).

The actual repository linked from the README is [browser-sync](https://www.npmjs.com/package/browser-sync).

index.js:

```js
const browserSync = require('browser-sync');
```

Which will throw:
```
Error: Cannot find module 'browser-sync'
```

**Comment by Yhimansh** [comment]
npm i browser-sync --save
npm start
